### ISSUE TITLE
Strange behavior when using widget in Application Builder when used on a Group Template dashboard

### ISSUE THREAD

**Issue by jmoo900** [SoftwareAG/cumulocity-datapoints-charting-widget-plugin#1]
Trying to use this widget to show a stacked bar chart across many devices using a group template dashboard.  Everything seems to work as expected during configuration, but when switching between devices, the original device remains visible.  If I clear the cache via the clear measurement cache button, then the correct data is displayed.  Seems like the cache is treating the chart as the same chart even though it is showing 2 different devices information.

**Comment by YashPShah-swag** [comment]
Fixed in 1.2.1 release, Thanks.
